src/main/java/fronteira/AcessoMB.java
package fronteira;

import controle.ControleDeAcesso;
import entidade.Usuario;
import java.io.Serializable;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

@ManagedBean(name = "acesso")
@SessionScoped
public class AcessoMB implements Serializable {

    private final Usuario usuario;
    private boolean logado;

    public AcessoMB() {
        usuario = new Usuario();
    }

    public void entrar() {
        logado = new ControleDeAcesso().validarAcesso(usuario);
        if (logado) {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_INFO, "Bem vindo!", "Bem vindo!"));
        } else {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_WARN, "Usuário ou senha incorreto", "Usuário ou senha incorreto"));
        }
    }

    public void sair() {
        logado = false;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public boolean isLogado() {
        return logado;
    }

}

src/main/java/fronteira/GerenciarLivroMB.java
package fronteira;

import controle.ControleDeEmprestimo;
import controle.ControleDeEspera;
import controle.ControleDeExemplares;
import controle.ControleDeLivro;
import entidade.Cliente;
import entidade.Emprestimo;
import entidade.Livro;
import entidade.Repositorio;
import java.io.Serializable;
import java.util.Collection;
import java.util.Deque;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

@ManagedBean(name = "gerenciarLivro")
@SessionScoped
public class GerenciarLivroMB implements Serializable {

    private final ControleDeLivro controleDeLivro;
    private final ControleDeEspera controleDeEspera;
    private final ControleDeEmprestimo controleDeEmprestimo;
    private final ControleDeExemplares controleDeExemplares;
    private List<Livro> resultadoDaPesquisa;
    private Livro livroAtual;
    private Livro livroAntigo;
    private Cliente cliente;
    private int numeroExemplares;
    private String ISBN;
    private String titulo;
    private String autor;
    private String editora;
    private String genero;
    private String ano;
    private String edicao;
    private String rg;
    private String nome;
    private String email;
    private String telefone;

    public GerenciarLivroMB() {
        controleDeLivro = new ControleDeLivro();
        controleDeEspera = new ControleDeEspera();
        controleDeEmprestimo = new ControleDeEmprestimo();
        controleDeExemplares = new ControleDeExemplares();
    }

    public void adicionarLivro() {
        if (controleDeLivro.adicionar(construirLivro())) {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_INFO, "Livro cadastrado", "Livro cadastrado"));
            limparDados();
        } else {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_WARN, "Falha", "Falha"));
        }
    }

    public void removerLivro(Livro livro) {
        if (controleDeLivro.remover(livro)) {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_INFO, "Livro removido", "Livro removido"));
            resultadoDaPesquisa.remove(livro);
        } else {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_WARN, "Falha", "Falha"));
        }
    }

    public String editarLivro(Livro livro) {
        this.livroAntigo = new Livro().copiarDe(livro);
        this.livroAtual = new Livro().copiarDe(livro);
        numeroExemplares = livro.getExemplares().size();
        return "editar";
    }

    public void atualizar() {
        controleDeExemplares.alterarTotalDeExemplares(livroAtual, numeroExemplares);
        if (controleDeLivro.atualizar(livroAntigo, livroAtual)) {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_INFO, "Livro atualizado", "Livro atualizado"));
        } else {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_WARN, "Falha", "Falha"));
        }
    }

    public String filaDeEspera(Livro livro) {
        this.livroAtual = new Livro().copiarDe(livro);
        limparDados();
        return "espera";
    }

    public void registrarEmprestimo() {
        Emprestimo emprestimo = new Emprestimo(livroAtual.getEspera().peek(), livroAtual);
        if (controleDeEmprestimo.realizarEmprestimo(emprestimo)) {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_INFO, "Empréstimo registrado", "Empréstimo registrado"));
        } else {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_WARN, "Falha", "Falha"));
        }
    }

    public void adicionarAFila() {
        Cliente c = new Cliente();
        c.setRg(rg);
        c.setNome(nome);
        c.setEmail(email);
        c.setTelefone(telefone);
        if (controleDeEspera.adicionarAFila(c, livroAtual)) {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_INFO, "Cliente adicionado à fila", "Cliente adicionado à fila"));
            limparDados();
        } else {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_WARN, "Falha", "Falha"));
        }
    }

    public void registrarDevolucao(Emprestimo emprestimo) {
        if (controleDeEmprestimo.registrarDevolucao(emprestimo)) {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_INFO, "Devolução registrada", "Devolução registrada"));
        } else {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_WARN, "Falha", "Falha"));
        }
    }

    public void disponibilizarExemplar() {
        if (controleDeEmprestimo.disponibilizarExemplar()) {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_INFO, "Exemplar disponível", "Exemplar disponível"));
        } else {
            FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_WARN, "Falha", "Falha"));
        }
    }

    public Collection<Livro> getLivros() {
        return Repositorio.getInstancia().livros();
    }

    public List<Emprestimo> getEmEmprestimo() {
        return Repositorio.getInstancia().emprestimo();
    }

    public Deque<Emprestimo> getDevolvido() {
        return Repositorio.getInstancia().devolucao();
    }

    public Collection<Livro> getResultadoDaPesquisa() {
        return resultadoDaPesquisa;
    }

    public void pesquisarLivro() {
        if (resultadoDaPesquisa != null) {
            resultadoDaPesquisa.clear();
        }
        resultadoDaPesquisa = controleDeLivro.pesquisar(construirLivro());
        limparDados();
    }

    private void limparDados() {
        ISBN = "";
        titulo = "";
        autor = "";
        editora = "";
        genero = "";
        ano = "";
        edicao = "";
        rg = "";
        nome = "";
        email = "";
        telefone = "";
    }

    private Livro construirLivro() {
        Livro l = new Livro();
        if (ISBN != null && !ISBN.isEmpty()) {
            l.setISBN(ISBN);
        }
        if (titulo != null && !titulo.isEmpty()) {
            l.setTitulo(titulo);
        }
        if (autor != null && !autor.isEmpty()) {
            l.setAutor(autor);
        }
        if (editora != null && !editora.isEmpty()) {
            l.setEditora(editora);
        }
        if (genero != null && !genero.isEmpty()) {
            l.setGenero(genero);
        }
        if (ano != null && !ano.isEmpty()) {
            l.setAno(ano);
        }
        if (edicao != null && !edicao.isEmpty()) {
            l.setEdicao(edicao);
        }
        return l;
    }

    public String getISBN() {
        return ISBN;
    }

    public void setISBN(String ISBN) {
        this.ISBN = ISBN;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getAutor() {
        return autor;
    }

    public void setAutor(String autor) {
        this.autor = autor;
    }

    public String getEditora() {
        return editora;
    }

    public void setEditora(String editora) {
        this.editora = editora;
    }

    public String getGenero() {
        return genero;
    }

    public void setGenero(String genero) {
        this.genero = genero;
    }

    public String getAno() {
        return ano;
    }

    public void setAno(String ano) {
        this.ano = ano;
    }

    public String getEdicao() {
        return edicao;
    }

    public void setEdicao(String edicao) {
        this.edicao = edicao;
    }

    public int getNumeroExemplares() {
        return numeroExemplares;
    }

    public void setNumeroExemplares(int numeroExemplares) {
        this.numeroExemplares = numeroExemplares;
    }

    public void setResultadoDaPesquisa(List<Livro> resultadoDaPesquisa) {
        this.resultadoDaPesquisa = resultadoDaPesquisa;
    }

    public Livro getLivro() {
        return livroAtual;
    }

    public void setLivro(Livro livro) {
        this.livroAtual = livro;
    }

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public String getRg() {
        return rg;
    }

    public void setRg(String rg) {
        this.rg = rg;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getTelefone() {
        return telefone;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

}

src/main/webapp/404.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"  
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:h="http://java.sun.com/jsf/html">

    <ui:composition template="/templates/template.xhtml">    
        <ui:define name="title">404 | Página não encontrada</ui:define>
        <ui:define name="content">   
            <h:form id="404" styleClass="col-xs-12 col-md-6" >
                <fieldset class="text-center">
                    <div class="col-xs-12">
                        <div class="col-xs-6">
                            <h1 class="error-code">404</h1>
                        </div>
                    </div>
                </fieldset>
                <fieldset class="text-center">
                    <hr />
                    <p class="text-danger">Página não encontrada!</p>
                    <h:commandLink styleClass="btn btn-lg btn-primary col-xs-12" action="login" >
                        <i class="glyphicon glyphicon-home"> </i> Ir à Página inicial
                    </h:commandLink>
                </fieldset>
            </h:form>
        </ui:define>
    </ui:composition>
</html>

src/main/webapp/500.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"  
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:h="http://java.sun.com/jsf/html">

    <ui:composition template="/templates/template.xhtml">    
        <ui:define name="title">500 | Erro Interno</ui:define>
        <ui:define name="content">   
            <h:form id="500" styleClass="col-xs-12 col-md-6" >
                <fieldset class="text-center">
                    <div class="col-xs-12">
                        <div class="col-xs-6">
                            <h1 class="error-code">500</h1>
                        </div>
                    </div>
                </fieldset>
                <fieldset class="text-center">
                    <hr />
                    <p class="text-danger">Ocorreu um erro na aplicação!</p>
                    <h:commandLink styleClass="btn btn-lg btn-primary col-xs-12"  action="login" >
                        <i class="glyphicon glyphicon-home"> </i> Ir à Página inicial
                    </h:commandLink>
                </fieldset>
                <hr/>
                <span id="view-error" class="btn btn-xs btn-default">
                    <i class="glyphicon glyphicon-eye-open"> </i>
                </span>
                <fieldset id="error-code" class="text-center">
                    <p class="my-pre">#{requestScope['javax.servlet.error.exception']}</p>
                </fieldset>
            </h:form>
        </ui:define>
    </ui:composition>
</html>

src/main/webapp/devolvido.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"  
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:h="http://java.sun.com/jsf/html"  
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/templates/template.xhtml">    
        <ui:define name="title">Fila de Espera</ui:define>
        <ui:define name="content">  
            <div class="col-sm-12">
                <h:form acceptcharset="ISO-8859-1" id="lista" styleClass="col-xs-12 box" >
                    <div class="row">
                        <div class="col-xs-12">
                            <label  ><strong>Exemplares devolvidos: #{gerenciarLivro.devolvido.size()}</strong></label>
                            <h:commandLink styleClass="btn btn-sm btn-info col-xs-12" action="#{gerenciarLivro.disponibilizarExemplar()}">
                                <i class="glyphicon glyphicon-check pull-left"> </i> Disponibilizar Exemplar
                            </h:commandLink>
                        </div>
                    </div>

                    <p:dataScroller value="#{gerenciarLivro.devolvido}" mode="inline" var="emprestimo" scrollHeight="500" chunkSize="10" >
                        <fieldset class="col-xs-12">
                            <div class="col-xs-12">
                                <div class="col-xs-6 col-sm-4">
                                    <label>#{emprestimo.livro.titulo}</label>
                                </div>
                                <div class="col-xs-6 col-sm-4">
                                    <label>#{emprestimo.livro.autor}</label>
                                </div>
                                <div class="col-xs-6 col-sm-4">
                                    <label>#{emprestimo.livro.ISBN}</label>
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <div class="col-xs-6 col-sm-3">
                                    <label>#{emprestimo.cliente.rg}</label>
                                </div>
                                <div class="col-xs-12 col-sm-3">
                                    <label>
                                        <strong>#{emprestimo.cliente.nome}</strong>
                                    </label>
                                </div>
                                <div class="col-xs-6 col-sm-3">
                                    <label class="text-info" >#{emprestimo.cliente.email}</label>
                                </div>
                                <div class="col-xs-6 col-sm-3">
                                    <label>#{emprestimo.cliente.telefone}</label>
                                </div>
                            </div>
                        </fieldset>
                    </p:dataScroller>

                </h:form>
            </div>            
        </ui:define>
    </ui:composition>
</html>

src/main/webapp/editar.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"  
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:h="http://java.sun.com/jsf/html"  
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/templates/template.xhtml">    
        <ui:define name="title">Editar</ui:define>
        <ui:define name="content">  
            <div class="col-sm-12">
                <h:form acceptcharset="ISO-8859-1" id="localizar" styleClass="col-xs-12 box">
                    <fieldset >
                        <div class="form-group col-xs-12 col-sm-4">
                            <label class="control-label" for="titulo" >Título</label>
                            <p:inputText placeholder="Título" value="#{gerenciarLivro.livro.titulo}" id="titulo" styleClass="form-control input-sm" />
                        </div>
                        <div class="form-group col-xs-12 col-sm-4">
                            <label class="control-label" for="autor" >Autor</label>
                            <p:inputText placeholder="Autor" value="#{gerenciarLivro.livro.autor}" id="autor" styleClass="form-control input-sm" />
                        </div>
                        <div class="form-group col-xs-12 col-sm-4">
                            <label class="control-label" for="editora" >Editora</label>
                            <p:inputText placeholder="Editora" value="#{gerenciarLivro.livro.editora}" id="editora" styleClass="form-control input-sm" />
                        </div>
                        <div class="form-group col-xs-12 col-sm-4">
                            <label class="control-label" for="genero" >Gênero</label>
                            <p:inputText placeholder="Gênero" value="#{gerenciarLivro.livro.genero}" id="genero" styleClass="form-control input-sm" />
                        </div>
                        <div class="form-group col-xs-12 col-sm-4">
                            <label class="control-label" for="isbn" >ISBN</label>
                            <p:inputText placeholder="ISBN" value="#{gerenciarLivro.livro.ISBN}" id="isbn" styleClass="form-control input-sm" />
                        </div>
                        <div class="form-group col-xs-6 col-sm-4">
                            <label class="control-label" for="ano" >Ano</label>
                            <p:inputText placeholder="Ano" value="#{gerenciarLivro.livro.ano}" id="ano" styleClass="form-control input-sm" />
                        </div>
                        <div class="form-group col-xs-6 col-sm-4">
                            <label class="control-label" for="edicao" >Edição</label>
                            <p:inputText placeholder="Edição" value="#{gerenciarLivro.livro.edicao}" id="edicao" styleClass="form-control input-sm" />
                        </div>
                        <div class="form-group col-xs-6 col-sm-4">
                            <label class="control-label" for="exemplares" >Número de Exemplares</label>
                            <p:spinner placeholder="Número de Exemplares" value="#{gerenciarLivro.numeroExemplares}" id="exemplares"  />
                        </div>
                        <div class="form-group col-xs-12 col-sm-12">
                            <h:commandLink styleClass="btn btn-sm btn-info col-xs-12" action="#{gerenciarLivro.atualizar()}">
                                <i class="glyphicon glyphicon-refresh pull-left"> </i> Atualizar
                            </h:commandLink>
                        </div>
                    </fieldset>
                </h:form>
            </div>            
        </ui:define>
        <ui:define name="javascripts">
            <script type="text/javascript" >
                $(".plus").on("click", function () {
                    $(this).parent("div").next("div").toggleClass("hide");
                });
            </script>   
        </ui:define>
    </ui:composition>
</html>

src/main/webapp/emprestado.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"  
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:h="http://java.sun.com/jsf/html"  
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/templates/template.xhtml">    
        <ui:define name="title">Fila de Espera</ui:define>
        <ui:define name="content">  
            <div class="col-sm-12">
                <h:form acceptcharset="ISO-8859-1" id="lista" styleClass="col-xs-12 box" >
                    <div class="row-fluid">
                        <label><strong>Exemplares emprestados: #{gerenciarLivro.emEmprestimo.size()}</strong></label>
                    </div>

                    <p:dataScroller value="#{gerenciarLivro.emEmprestimo}" mode="inline" var="emprestimo" scrollHeight="500" chunkSize="10" >
                        <fieldset class="col-xs-12">
                            <div class="col-xs-10 col-sm-10 ">
                                <div class="col-xs-6 col-sm-4">
                                    <label>#{emprestimo.livro.titulo}</label>
                                </div>
                                <div class="col-xs-6 col-sm-4">
                                    <label>#{emprestimo.livro.autor}</label>
                                </div>
                                <div class="col-xs-6 col-sm-4">
                                    <label>#{emprestimo.livro.ISBN}</label>
                                </div>
                            </div>
                            <div class="col-xs-10 col-sm-10 ">
                                <div class="col-xs-6 col-sm-3">
                                    <label>#{emprestimo.cliente.rg}</label>
                                </div>
                                <div class="col-xs-12 col-sm-3">
                                    <label>
                                        <strong>#{emprestimo.cliente.nome}</strong>
                                    </label>
                                </div>
                                <div class="col-xs-6 col-sm-3">
                                    <label class="text-info" >#{emprestimo.cliente.email}</label>
                                </div>
                                <div class="col-xs-6 col-sm-3">
                                    <label>#{emprestimo.cliente.telefone}</label>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-4 col-lg-2 ">
                                <h:commandLink styleClass="btn btn-sm btn-info col-xs-12" action="#{gerenciarLivro.registrarDevolucao(emprestimo)}">
                                    <i class="glyphicon glyphicon-check pull-left"> </i> Registrar Devolução
                                </h:commandLink>
                            </div>
                        </fieldset>
                    </p:dataScroller>

                </h:form>
            </div>            
        </ui:define>
    </ui:composition>
</html>

src/main/webapp/espera.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"  
      xmlns:ui="http://java.sun.com/jsf/facelets" 
      xmlns:h="http://java.sun.com/jsf/html"  
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/templates/template.xhtml">    
        <ui:define name="title">Fila de Espera</ui:define>
        <ui:define name="content">  
            <div class="col-sm-12">
                <h:form acceptcharset="ISO-8859-1" id="lista" styleClass="col-xs-12 box" rendered="#{gerenciarLivro.livro ne null}">
                    <fieldset >
                        <div class="col-xs-10 col-sm-12 pull-left">
                            <div class="col-xs-12 col-sm-12">
                                <label>
                                    <strong>#{gerenciarLivro.livro.titulo}</strong>
                                </label>
                            </div>
                            <div class="col-xs-6 col-sm-6">
                                <label class="text-info" >#{gerenciarLivro.livro.autor}</label>
                            </div>
                            <div class="col-xs-6 col-sm-6">
                                <label>#{gerenciarLivro.livro.editora}</label>
                            </div>
                            <div class="col-xs-6 col-sm-3">
                                <label>#{gerenciarLivro.livro.genero}</label>
                            </div>
                            <div class="col-xs-6 col-sm-3">
                                <label>#{gerenciarLivro.livro.ISBN}</label>
                            </div>
                            <div class="col-xs-6 col-sm-3">
                                <label>#{gerenciarLivro.livro.ano}</label>
                            </div>
                            <div class="col-xs-6 col-sm-3">
                                <label>#{gerenciarLivro.livro.edicao}</label>
                            </div>
                        </div>

                        <div class="col-xs-10 col-sm-12 pull-left">
                            <div class="form-group col-xs-12 col-sm-3">
                                <p:inputText placeholder="RG" value="#{gerenciarLivro.rg}" id="rg" styleClass="form-control input-sm" />
                            </div>
                            <div class="form-group col-xs-12 col-sm-3">
                                <p:inputText placeholder="Nome" value="#{gerenciarLivro.nome}" id="nome" styleClass="form-control input-sm" />
                            </div>
                            <div class="form-group col-xs-12 col-sm-3">
                                <p:inputText placeholder="e-mail" value="#{gerenciarLivro.email}" id="email" styleClass="form-control input-sm" />
                            </div>
                            <div class="form-group col-xs-12 col-sm-3">
                                <p:inputText placeholder="Telefone" value="#{gerenciarLivro.telefone}" id="telefone" styleClass="form-control input-sm" />
                            </div>
                            <div class="form-group col-xs-12 col-sm-12">
                                <h:commandLink styleClass="btn btn-sm btn-info col-xs-12" action="#{gerenciarLivro.adicionarAFila()}">
                                    <i class="glyphicon glyphicon-plus-sign pull-left"> </i> Adicionar à Fila de Espera
                                </h:commandLink>
                            </div>
                        </div>
                        <div class="form-group col-xs-12 col-sm-12">
                            <h:commandLink 
                                action="#{gerenciarLivro.registrarEmprestimo()}"
                                styleClass="btn btn-sm btn-success col-xs-12 #{gerenciarLivro.livro.espera.size() > 0 ? '' : 'disabled'}" >
                                <i class="glyphicon glyphicon-bookmark pull-left"> </i> Registrar Empréstimo
                            </h:commandLink>
                        </div>
                    </fieldset>
                    <div class="row-fluid">
                        <label><strong>Em espera: #{gerenciarLivro.livro.espera.size()}</strong></label>
                    </div>


                    <p:dataScroller value="#{gerenciarLivro.livro.espera}" mode="inline" var="cliente" scrollHeight="200" 
                                    chunkSize="10" rendered="#{gerenciarLivro.livro.espera.size() > 0}">
                        <fieldset >
                            <div class="col-xs-10 col-sm-12 pull-left">
                                <div class="col-xs-6 col-sm-3">
                                    <label>#{cliente.rg}</label>
                                </div>
                                <div class="col-xs-12 col-sm-3">
                                    <label>
                                        <strong>#{cliente.nome}</strong>
                                    </label>
                                </div>
                                <div class="col-xs-6 col-sm-3">
                                    <label class="text-info" >#{cliente.email}</label>
                                </div>
                                <div class="col-xs-6 col-sm-3">
                                    <label>#{cliente.telefone}</label>
                                </div>
                            </div>
                        </fieldset>
                    </p:dataScroller>

                </h:form>
            </div>            
        </ui:define>
    </ui:composition>
</html>